version: '3.8'

services:
  db:
    image: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: userreg
    volumes:
        - ./postgresql:/var/lib/postgresql/data
    networks:
      - userregnetwork

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    ports:
      - "8081:8081"
    expose:
      - 8081
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_DISABLE_POSTFIX: false
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
      PGADMIN_LISTEN_PORT: 8081
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    networks:
      - userregnetwork

networks:
  userregnetwork:
    driver: bridge