server:
  port : 8180
app:
  opa:
    authz:
      url: http://localhost:8181/v1/data/
management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    root: INFO
    org:
      springframework:
        security: DEBUG
        web: DEBUG
spring:
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: full
  profiles:
        active: default
  datasource:
          driver-class-name: org.postgresql.Driver
          username: postgres
          password: password
          name: userreg
          url: jdbc:postgresql://localhost:5432/userreg?createDatabaseIfNotExist=true
  sql:
      init:
        mode: always # you won't do this in prod, I'm just doing this for demo purposes
info:
  application:
    name: User Registration
    description: A user Registration application
    author: Stig B. Sivertsen
    version: '@project.version@'
