server:
  port : 8180
  #context-path: /usereg 
app:
  opa:
    authz:
      url: http://opa:8181/v1/data/
management:
  endpoints:
    web:
      exposure:
        include: '*'
#debug: true
logging:
  level:
    [no.sivertsensoftware]: TRACE
    root: INFO
    web: TRACE
    org:
      hibernate: DEBUG
      springframework:
        security: TRACE
        web: TRACE
spring:
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 10000
            readTimeout: 10000
            loggerLevel: full
  profiles:
        active: default
  datasource:
          driver-class-name: org.postgresql.Driver
          username: postgres
          password: password
          name: userreg
          url: jdbc:postgresql://db:5432/userreg?createDatabaseIfNotExist=true
  sql:
      init:
        mode: always # you won't do this in prod, I'm just doing this for demo purposes
info:
  application:
    name: Contact Registration
    description: A Contact Registration application, ${app.name}
    author: Stig B. Sivertsen
    version: '@project.version@'
